# This is a basic workflow to help you get started with Actions

name: Build Github Profile

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  '40 16 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # set china timezone
    env:
      TZ: Asia/Shanghai

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get user name and email, and set to env
        uses: actions/github-script@v4
        id: user-config
        with:
          result-encoding: json
          script: |
            console.log(context)
            const { pusher } = context.payload
            console.log(pusher)
            return pusher

      - name: List git config
        run: git config --list

      - name: Echo
        run: echo "${{fromJSON(steps.user-config.outputs).name}}"

      - name: Set git commit author
        run: |
          git config --global user.name ${{fromJSON(steps.user-config.outputs).name}}
          git config --global user.email ${{fromJSON(steps.user-config.outputs).email}}

      - name: List git config
        run: git config --list

      # Runs a set of commands using the runners shell
      - name: Install package
        run: yarn

      - name: Build
        run: yarn build

      - name: Update GitHub Profile
        run: |
          git diff
          git pull
          git add -A
          git commit -m "Update README" || exit 0


